### PR TITLE
Adding emacs lite package

### PR DESCRIPTION
**Pull request by kiennq**
This is emacs lite package that showing the configuration in #1

### CODE REVIEW

**Comment by enko** [comment]
@kiennq nice one! I'm currently testing this. Why did you name it emacsw-lite and not emacs-lite? Are there any specific reasons?

**Comment by enko** [comment]
The lite package works just fine, even with the fancy tls stuff and all. I'm wondering if the lite package should be the standard and there should be an emacs-full package for the complete experience. What do you think @kiennq ?

**Comment by kiennq** [comment]
> @kiennq nice one! I'm currently testing this. Why did you name it emacsw-lite and not emacs-lite? Are there any specific reasons?

No, I just pick up the name emacsw-lite before and already submitted a Chocolatey package for it a month before https://chocolatey.org/packages/emacsw-lite.
It's still waiting for approval though.
Using the name emacs-lite is complete fine to me.

> The lite package works just fine, even with the fancy tls stuff and all. I'm wondering if the lite package should be the standard and there should be an emacs-full package for the complete experience. What do you think @kiennq ?

It would be great. I'm complete agree with that.
Let me get back to you with a change for that

**Comment by kiennq** [comment]
@enko Can you please take a look at this PR

**Comment by enko** [comment]
@kiennq Sorry, my week was a bit full, this looks very good! I'm merging it.

**Pull request merged**
